// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UspJsonTest.Models
{
    public partial class Sp_Json_Result
    {
        [Column("JSON_F52E2B61-18A1-11d1-B105-00805F49916B")]
        public string json { get; set; }
    }
}
