// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UspJsonTest.Models
{
    [Table("tblCustomer")]
    public partial class TblCustomer
    {
        [Key]
        public int Id { get; set; }
        [StringLength(128)]
        public string Name { get; set; }
        [StringLength(15)]
        public string Mobile { get; set; }
        [StringLength(128)]
        public string Email { get; set; }
        public int? StateId { get; set; }
        public int? CityId { get; set; }
        [Column("pincode")]
        public int? Pincode { get; set; }

        [ForeignKey(nameof(CityId))]
        [InverseProperty(nameof(TblCity.TblCustomers))]
        public virtual TblCity City { get; set; }
        [ForeignKey(nameof(StateId))]
        [InverseProperty(nameof(TblState.TblCustomers))]
        public virtual TblState State { get; set; }
    }
}