// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UspJsonTest.Models
{
    [Table("tblCity")]
    public partial class TblCity
    {
        public TblCity()
        {
            TblCustomers = new HashSet<TblCustomer>();
        }

        [Key]
        public int CityId { get; set; }
        [StringLength(128)]
        public string CityName { get; set; }
        public int? StateId { get; set; }

        [ForeignKey(nameof(StateId))]
        [InverseProperty(nameof(TblState.TblCities))]
        public virtual TblState State { get; set; }
        [InverseProperty(nameof(TblCustomer.City))]
        public virtual ICollection<TblCustomer> TblCustomers { get; set; }
    }
}